services:
  db:
    image: postgres:15
    container_name: stomatology_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-stomatology_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-stomatology123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped

volumes:
  postgres_data: