# Generated by Django 4.2.7 on 2025-06-27 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('green_threshold', models.FloatField(default=80, help_text='Green zone starts at this percentage of max value', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('yellow_threshold', models.FloatField(default=60, help_text='Yellow zone starts at this percentage of max value', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (e.g., mm, %, points)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
