# Generated by Django 4.2.7 on 2025-06-28 06:57

from django.db import migrations, models
import django.core.validators


def create_schema_model(apps, schema_editor):
    """Create Schema model first"""
    pass


def create_default_schema(apps, schema_editor):
    """Create default schema for existing indicators"""
    Schema = apps.get_model('indicators', 'Schema')
    Schema.objects.create(
        name='Primary Health Indicators',
        description='Original 6 health indicators for stomatology assessment',
        order=1,
        is_active=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        # First create the Schema model
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order (1=first, 2=second, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        # Create default schema
        migrations.RunPython(create_default_schema),
    ]
