# Generated by Django 4.2.7 on 2025-06-28 06:58

from django.db import migrations


def assign_schema_to_indicators(apps, schema_editor):
    """Assign default schema to all existing indicators"""
    Schema = apps.get_model('indicators', 'Schema')
    Indicator = apps.get_model('indicators', 'Indicator')
    
    # Get the default schema
    default_schema = Schema.objects.get(name='Primary Health Indicators')
    
    # Assign it to all indicators that don't have a schema
    Indicator.objects.filter(schema__isnull=True).update(schema=default_schema)


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_add_schema_to_indicator'),
    ]

    operations = [
        migrations.RunPython(assign_schema_to_indicators),
    ]
