# Generated by Django 4.2.7 on 2025-06-28 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_add_step_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='zero_value_score',
            field=models.IntegerField(choices=[(0, '0 points'), (1, '1 point'), (2, '2 points')], default=0, help_text="Score when value is 0 or empty (e.g., 0 points for 'Does not smoke')"),
        ),
        migrations.AlterField(
            model_name='scoringrange',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
