# Generated by Django 4.2.7 on 2025-06-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_update_max_score_to_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий риск'), ('moderate', 'Умеренный риск'), ('high', 'Высокий риск')], max_length=20)),
                ('min_score', models.IntegerField(help_text='Minimum total score for this risk level')),
                ('max_score', models.IntegerField(help_text='Maximum total score for this risk level')),
                ('title', models.CharField(help_text='Title of the risk assessment', max_length=200)),
                ('description', models.TextField(help_text='Description of the risk level')),
                ('recommendations', models.TextField(help_text='Detailed medical recommendations')),
                ('indicator_recommendations', models.JSONField(default=dict, help_text='Specific recommendations for each indicator (JSON format)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_templates', to='indicators.schema')),
            ],
            options={
                'ordering': ['schema', 'min_score'],
                'unique_together': {('schema', 'risk_level')},
            },
        ),
    ]
