# Generated by Django 4.2.7 on 2025-07-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_add_recommendation_templates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendationtemplate',
            options={'ordering': ['schema', 'min_score'], 'verbose_name': 'Шаблон рекомендаций', 'verbose_name_plural': 'Шаблоны рекомендаций'},
        ),
        migrations.AlterModelOptions(
            name='schema',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Схема', 'verbose_name_plural': 'Схемы'},
        ),
        migrations.AlterField(
            model_name='recommendationtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='recommendationtemplate',
            name='description',
            field=models.TextField(help_text='Описание уровня риска', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recommendationtemplate',
            name='indicator_recommendations',
            field=models.JSONField(default=dict, help_text='Специфические рекомендации для каждого индикатора (JSON формат)', verbose_name='Рекомендации по индикаторам'),
        ),
        migrations.AlterField(
            model_name='recommendationtemplate',
            name='max_score',
            field=models.IntegerField(help_text='Максимальный общий балл для этого уровня риска', verbose_name='Максимальный балл'),
        ),
        migrations.AlterField(
            model_name='recommendationtemplate',
            name='min_score',
            field=models.IntegerField(help_text='Минимальный общий балл для этого уровня риска', verbose_name='Минимальный балл'),
        ),
        migrations.AlterField(
            model_name='recommendationtemplate',
            name='recommendations',
            field=models.TextField(help_text='Подробные медицинские рекомендации', verbose_name='Рекомендации'),
        ),
        migrations.AlterField(
            model_name='recommendationtemplate',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Низкий риск'), ('moderate', 'Умеренный риск'), ('high', 'Высокий риск')], max_length=20, verbose_name='Уровень риска'),
        ),
        migrations.AlterField(
            model_name='recommendationtemplate',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_templates', to='indicators.schema', verbose_name='Схема'),
        ),
        migrations.AlterField(
            model_name='recommendationtemplate',
            name='title',
            field=models.CharField(help_text='Заголовок оценки риска', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='recommendationtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Порядок отображения (1=первая, 2=вторая, и т.д.)', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
    ]
