# Generated by Django 4.2.7 on 2025-07-03 19:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_alter_recommendationtemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['schema__order', 'name'], 'verbose_name': 'Индикатор', 'verbose_name_plural': 'Индикаторы'},
        ),
        migrations.AlterField(
            model_name='indicator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='max_value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальное значение'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='min_value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальное значение'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='indicators.schema', verbose_name='Схема'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
