# Generated by Django 4.2.7 on 2025-07-03 19:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_alter_indicator_options_alter_indicator_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoringrange',
            options={'ordering': ['indicator', 'score'], 'verbose_name': 'Диапазон оценок', 'verbose_name_plural': 'Диапазоны оценок'},
        ),
        migrations.AlterField(
            model_name='scoringrange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='scoringrange',
            name='description',
            field=models.CharField(help_text="Описание как '0-28', '≥20', 'Не курит'", max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='scoringrange',
            name='exact_value',
            field=models.FloatField(blank=True, help_text='Точное совпадение значения (для конкретных значений как 0, 1, 2)', null=True, verbose_name='Точное значение'),
        ),
        migrations.AlterField(
            model_name='scoringrange',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_ranges', to='indicators.indicator', verbose_name='Индикатор'),
        ),
        migrations.AlterField(
            model_name='scoringrange',
            name='is_greater_than_or_equal',
            field=models.BooleanField(default=False, help_text='≥ минимального значения (игнорирует максимальное значение)', verbose_name='Больше или равно'),
        ),
        migrations.AlterField(
            model_name='scoringrange',
            name='is_less_than',
            field=models.BooleanField(default=False, help_text='< максимального значения (игнорирует минимальное значение)', verbose_name='Меньше чем'),
        ),
        migrations.AlterField(
            model_name='scoringrange',
            name='max_value',
            field=models.FloatField(blank=True, help_text='Максимальное значение (включительно)', null=True, verbose_name='Максимальное значение'),
        ),
        migrations.AlterField(
            model_name='scoringrange',
            name='min_value',
            field=models.FloatField(blank=True, help_text='Минимальное значение (включительно)', null=True, verbose_name='Минимальное значение'),
        ),
        migrations.AlterField(
            model_name='scoringrange',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='scoringrange',
            name='step',
            field=models.FloatField(default=1.0, help_text='Шаг между минимальным и максимальным значениями (по умолчанию: 1)', verbose_name='Шаг'),
        ),
    ]
