# Generated by Django 4.2.7 on 2025-07-03 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0011_alter_scoringrange_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationtemplate',
            name='indicator_recommendations',
            field=models.JSONField(blank=True, default=dict, help_text='УСТАРЕЛО: Используйте отдельные рекомендации по индикаторам', verbose_name='Рекомендации по индикаторам (устарело)'),
        ),
        migrations.CreateModel(
            name='IndicatorRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField(help_text='Рекомендация для этого индикатора при данном уровне риска', verbose_name='Текст рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator', verbose_name='Индикатор')),
                ('recommendation_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_recommendations_new', to='indicators.recommendationtemplate', verbose_name='Шаблон рекомендаций')),
            ],
            options={
                'verbose_name': 'Рекомендация по индикатору',
                'verbose_name_plural': 'Рекомендации по индикаторам',
                'ordering': ['recommendation_template', 'indicator__name'],
                'unique_together': {('recommendation_template', 'indicator')},
            },
        ),
    ]
