# Generated by Django 4.2.7 on 2025-07-03 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-login_time'], 'verbose_name': 'Сессия пользователя', 'verbose_name_plural': 'Сессии пользователей'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, help_text='Отделение или специальность', max_length=100, null=True, verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active_staff',
            field=models.BooleanField(default=True, help_text='Является ли этот сотрудник активным в настоящее время', verbose_name='Активный сотрудник'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='license_number',
            field=models.CharField(blank=True, help_text='Номер медицинской лицензии для врачей', max_length=50, null=True, verbose_name='Номер лицензии'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Врач'), ('nurse', 'Медсестра'), ('admin', 'Администратор'), ('researcher', 'Исследователь')], default='nurse', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время входа'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время выхода'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(max_length=40, verbose_name='Ключ сессии'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_log', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
    ]
