# Generated by Django 4.2.7 on 2025-06-27 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('show_in_chart', models.BooleanField(default=True, help_text='Show this measurement in radar chart')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='patients.patient')),
            ],
            options={
                'ordering': ['-measurement_date'],
                'unique_together': {('patient', 'measurement_date')},
            },
        ),
        migrations.CreateModel(
            name='MeasurementValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='measurements.measurement')),
            ],
            options={
                'unique_together': {('measurement', 'indicator')},
            },
        ),
    ]
