# Generated by Django 4.2.7 on 2025-07-03 19:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patient_options_alter_patienthistory_options_and_more'),
        ('indicators', '0010_alter_indicator_options_alter_indicator_created_at_and_more'),
        ('measurements', '0005_update_max_score_to_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-measurement_date'], 'verbose_name': 'Измерение', 'verbose_name_plural': 'Измерения'},
        ),
        migrations.AlterModelOptions(
            name='measurementvalue',
            options={'verbose_name': 'Значение измерения', 'verbose_name_plural': 'Значения измерений'},
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_date',
            field=models.DateTimeField(verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='show_in_chart',
            field=models.BooleanField(default=True, help_text='Показывать это измерение на радарной диаграмме', verbose_name='Показывать на диаграмме'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='measurementvalue',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator', verbose_name='Индикатор'),
        ),
        migrations.AlterField(
            model_name='measurementvalue',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='measurements.measurement', verbose_name='Измерение'),
        ),
        migrations.AlterField(
            model_name='measurementvalue',
            name='value',
            field=models.IntegerField(help_text='Значение балла (0-2 балла)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Значение'),
        ),
    ]
