# Generated by Django 4.2.7 on 2025-06-27 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='0', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number can contain digits, spaces, +, -, ( )', regex='^[\\d\\s\\+\\-\\(\\)]{1,20}$')]),
        ),
    ]
