# Generated by Django 4.2.7 on 2025-06-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='history_of_illness',
            field=models.TextField(blank=True, help_text='Medical history and previous illnesses'),
        ),
    ]
