# Generated by Django 4.2.7 on 2025-06-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_history_of_illness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='history_of_illness',
            field=models.CharField(help_text='Medical history number (unique identifier)', max_length=10, unique=True),
        ),
    ]
